"""Core Snowl protocols and data contracts."""

from snowl.core.agent import (
    Action,
    Agent,
    AgentContext,
    AgentState,
    Observation,
    StopReason,
    agent,
    validate_agent,
)
from snowl.core.agent_variant import (
    AgentVariant,
    AgentVariantAdapter,
    bind_agent_variant,
    make_agent_variant,
    validate_agent_variant,
)
from snowl.core.env import (
    EnvSpec,
    FileOps,
    ProcessOps,
    SandboxSpec,
    WebOps,
    ensure_tool_ops_compatible,
    validate_env_spec,
)
from snowl.core.scorer import (
    Score,
    ScoreContext,
    Scorer,
    scorer,
    validate_scorer,
    validate_scores,
)
from snowl.core.task import (
    Task,
    TaskProvider,
    task,
    validate_task,
    validate_task_provider,
)
from snowl.core.task_result import (
    ArtifactRef,
    ErrorInfo,
    TaskResult,
    TaskStatus,
    Timing,
    Usage,
    validate_task_result,
)
from snowl.core.tool import (
    ToolRegistry,
    ToolSpec,
    build_tool_spec,
    get_default_tool_registry,
    resolve_tool_spec,
    tool,
)

__all__ = [
    "Action",
    "Agent",
    "AgentContext",
    "AgentState",
    "AgentVariant",
    "AgentVariantAdapter",
    "ArtifactRef",
    "EnvSpec",
    "ErrorInfo",
    "FileOps",
    "Observation",
    "ProcessOps",
    "SandboxSpec",
    "Score",
    "ScoreContext",
    "Scorer",
    "StopReason",
    "Task",
    "TaskProvider",
    "TaskResult",
    "TaskStatus",
    "Timing",
    "ToolRegistry",
    "ToolSpec",
    "Usage",
    "WebOps",
    "ensure_tool_ops_compatible",
    "validate_agent",
    "validate_agent_variant",
    "validate_env_spec",
    "build_tool_spec",
    "bind_agent_variant",
    "get_default_tool_registry",
    "make_agent_variant",
    "resolve_tool_spec",
    "tool",
    "task",
    "agent",
    "scorer",
    "validate_scorer",
    "validate_scores",
    "validate_task",
    "validate_task_provider",
    "validate_task_result",
]
